name: shop_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #state management
  provider: ^4.1.3
  #util
  intl: ^0.16.1
  equatable: ^1.2.0
  #image
  cached_network_image: ^2.2.0+1
  #design
  shimmer: ^1.1.1
  badges: ^1.1.1
  modal_bottom_sheet: ^0.1.6+1
  flutter_colorpicker: ^0.3.4
  #network
  http: ^0.12.1
  json_serializable: ^3.3.0
  retrofit: ^1.3.4
  dio: ^3.0.9
  logger: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.7+2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 200
