name: api_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # json
  json_serializable: ^3.2.5
  # dio
  dio: ^3.0.8
  # dio conversion
  retrofit: ^1.3.0
  logger: ^0.8.3
  # log
  pretty_dio_logger: ^1.1.0
  provider: ^4.0.4
  #image
  # cache_image: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  # dio conversion
  retrofit_generator: ^1.3.0

flutter:
  uses-material-design: true
