name: complex_api_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
    ^0.1.2
    # json
  json_serializable: ^3.2.5
  # dio
  dio: ^3.0.8
  # dio conversion
  retrofit: ^1.3.0
  logger: ^0.8.3
  # log
  pretty_dio_logger: ^1.1.0
  provider: ^4.0.4
  cached_network_image: ^2.0.0
  # date format
  intl: ^0.16.1
  # pagenation
  pull_to_refresh: ^1.5.8
  # db
  moor_flutter: ^2.1.1
  path_provider: ^1.6.1
  # chrome debug
  flutter_stetho: ^0.5.2
  # internet connection
  connectivity: ^0.4.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  # dio conversion
  retrofit_generator: ^1.3.0
  # db
  moor_generator: ^2.4.0

flutter:
  uses-material-design: true
  fonts:
    - family: MyanmarNayone
      fonts:
        - asset: assets/fonts/MyanmarNayone.ttf
