name: bloc_api_demo
description: Implement BLoc design.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  json_serializable: ^3.3.0
  retrofit: ^1.3.4
  dio: ^3.0.9
  provider: ^4.1.3
  #logger: ^0.9.1
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^2.2.0+1
  path_provider: ^1.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.7
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
