name: book_moor
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_stetho: ^0.5.2
  moor: ^2.3.0
  moor_flutter: ^2.0.0
  path_provider: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.3.1
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
  assets:
    - assets/
